def raise_exception(header, err):
    print(header)
    print(err)